# ===============================
# SERVIDOR
# ===============================
server.servlet.context-path=${SERVER_CONTEXT_PATH}
server.port=${SERVER_PORT}

# ===============================
# SWAGGER / API DOCS
# ===============================
springdoc.swagger-ui.path=${SWAGGER_UI_PATH}
springdoc.api-docs.path=${API_DOCS_PATH}
springdoc.swagger-ui.url=${SWAGGER_UI_URL}
springdoc.swagger-ui.config-url=${SWAGGER_UI_CONFIG_URL}
springdoc.swagger-ui.disable-swagger-default-url=${SWAGGER_UI_DISABLE_DEFAULT}
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method

# ===============================
# ?BASE DE DATOS
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=${DB_DRIVER}

#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
#spring.jpa.show-sql=${JPA_SHOW_SQL}
#spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
#spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL}

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGIN}

# ===============================
# OAUTH2 (Azure AD)
# ===============================

# Proveedor (endpoints de Azure)
azure.client-id=${AZ_CLIENT_ID}
azure.tenant-id=${AZ_TENANT_ID}
azure.client-secret=${AZ_CLIENT_SECRET}

# ===============================
# JWT interno
# ===============================
app.jwt.secret=${JWT_SECRET}
spring.profiles.active=dev


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZ_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/${AZ_TENANT_ID}/discovery/v2.0/keys


logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.resourceserver=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
