server.servlet.context-path=${SERVER_CONTEXT_PATH}
server.port=${SERVER_PORT}

springdoc.swagger-ui.path=${SWAGGER_UI_PATH}
springdoc.api-docs.path=${API_DOCS_PATH}
springdoc.swagger-ui.url=${SWAGGER_UI_URL}
springdoc.swagger-ui.config-url=${SWAGGER_UI_CONFIG_URL}
springdoc.swagger-ui.disable-swagger-default-url=${SWAGGER_UI_DISABLE_DEFAULT}

logging.level.org.springframework=${LOG_SPRING}
logging.level.com.micolegio=${LOG_APP}

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#spring.datasource.driver-class-name=${DB_DRIVER}

#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
#spring.jpa.show-sql=${JPA_SHOW_SQL}
#spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
#spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL}

logging.level.org.hibernate.SQL=${LOG_HIBERNATE_SQL}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOG_BINDER}
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=${LOG_SQL_EXCEPTION}
logging.level.org.springframework.dao=${LOG_SPRING_DAO}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
